# Données du tableau : sources, chiffres, données manquantes, calculs propres
V_A = "A - Relu dans la source primaire"
V_B = "B - Source primaire consultée pendant la recherche (non relue)"
V_C = "C - Via un relais (presse, synthèse, autre rapport)"
V_D = "D - Non vérifié : origine à confirmer"
V_E = "E - Repris de la présentation OCDE (non revérifié)"

T_STAT = "Statistique publique"
T_INST = "Rapport institutionnel (Cour des comptes, Parlement, inspections, mission)"
T_ADM = "Administration / opérateur public"
T_PRIV = "Fédération ou cabinet privé"
T_PRESSE = "Presse / média spécialisé"
T_ACAD = "Recherche académique / CAE"
T_LOI = "Texte juridique"

SOURCES = [
 # ref, organisme, titre, date, type, lien
 ("S01","Cerema","Accompagner la mutation des zones commerciales de périphérie","19/05/2025",T_ADM,"https://www.cerema.fr/fr/actualites/accompagner-mutation-zones-commerciales-peripherie"),
 ("S02","Cerema","Les données de géolocalisation des 1500 zones commerciales de périphérie sont en open data (base EmpCom)","23/01/2024",T_ADM,"https://www.cerema.fr/fr/actualites/donnees-geolocalisation-1500-zones-commerciales-peripherie"),
 ("S03","Cerema","Zones commerciales et centres-villes : trouver le bon équilibre","s.d. (vers 2020-2021)",T_ADM,"https://www.cerema.fr/fr/actualites/zones-commerciales-centres-villes-trouver-bon-equilibre"),
 ("S04","Cerema","Déterminer le potentiel de réindustrialisation des friches dans les zones commerciales","28/11/2024",T_ADM,"https://www.cerema.fr/fr/actualites/potentiel-reindustrialisation-friches"),
 ("S05","Bédué M. et Cohen C. (Insee)","Le commerce de proximité : des pôles plus florissants en périphérie qu'en centre-ville, Insee Première n° 1858","20/05/2021",T_STAT,"https://www.insee.fr/fr/statistiques/5386414"),
 ("S06","Cazaubiel A. et Guymarc G. (Insee)","Commerce de proximité dans les villes de taille intermédiaire, Insee Première n° 1782","14/11/2019",T_STAT,"https://www.insee.fr/fr/statistiques/4248184"),
 ("S07","Bloch K. et Pichavant A.-S. (Insee)","Entre 2016 et 2022, l'emploi salarié des points de vente progresse davantage en dehors des centres-villes, Insee Première n° 2091","27/01/2026",T_STAT,"https://www.insee.fr/fr/statistiques/8730497"),
 ("S08","Gouvernement (ministères Économie, Transition écologique, Cohésion des territoires)","Un nouvel horizon pour les zones commerciales, dossier de presse","09/2023",T_ADM,"https://www.info.gouv.fr/upload/media/content/0001/07/2dc90efc2c1a0e97572bf027240fac63e4dc9d75.pdf"),
 ("S09","Procos","Dossier de presse, conférence annuelle","12/02/2025",T_PRIV,"https://www.procos.org/images/procos/presse/2025/Conf_0225/procos_dp_120225_site.pdf"),
 ("S10","CNAC / Direction générale des Entreprises","Rapport d'activité 2024 de la Commission nationale d'aménagement commercial","2025",T_ADM,"https://www.entreprises.gouv.fr/files/files/Publications/2025/rapports-activite/ra-cnac-2024.pdf"),
 ("S11","Icade et SCET","Baromètre des entrées de ville, 2e édition : cap sur les projets","09/2026",T_PRIV,"https://www.icade.fr/content/download/7372/file/barom%C3%A8tre-entr%C3%A9es-de-ville-2e-edition-cap-sur-projets.pdf"),
 ("S12","Allain M.-L. et Epaulard A. (CAE)","Petits commerces : déclin ou mutation ?, Les notes du CAE n° 77","05/2023",T_ACAD,"https://www.cae-eco.fr/"),
 ("S13","Rexecode","Répartition des ventes du commerce de détail par lieu de vente, d'après Insee, Procos et Fevad","2024",T_PRIV,""),
 ("S14","Codata","Codata Digest 2026 (relayé par L'Échommerces)","2026",T_PRIV,"https://lechommerces.fr/la-vacance-commerciale-progresse-de-nouveau-en-france/"),
 ("S15","L'Échommerces, d'après Codata","La vacance commerciale progresse de nouveau en France","2025",T_PRESSE,"https://lechommerces.fr/la-vacance-commerciale-progresse-de-nouveau-en-france/"),
 ("S16","Codata","Quel bilan tirer du plan ACV sur la vacance commerciale des centres-villes de villes moyennes ? (étude Codata / FACT)","s.d. (données 2018-2022)",T_PRIV,"https://www.codata.eu/blog/quel-bilan-tirer-du-plan-acv-sur-la-vacance-commerciale-des-centres-villes-de-villes-moyennes/"),
 ("S17","Points de Vente, d'après le baromètre Codata / FACT","La hausse de la vacance commerciale reprend dans les centres-villes","23/05/2024",T_PRESSE,"https://pointsdevente.fr/fil-info/2024-05-23-la-hausse-de-la-vacance-commerciale-reprend-dans-les-centres-villes/"),
 ("S18","Public Sénat, citant un rapport du CGEDD (2016)","Revitalisation des centres-villes : un rapport du Sénat pointe un sous-financement","2022",T_PRESSE,"https://www.publicsenat.fr/actualites/territoires/revitalisation-des-centres-villes-un-rapport-du-senat-pointe-un-sous"),
 ("S19","CGEDD et IGF (cité par le Cerema)","Rapport interministériel sur la revitalisation commerciale des centres-villes","2016",T_INST,"https://www.cerema.fr/fr/actualites/zones-commerciales-centres-villes-trouver-bon-equilibre"),
 ("S20","Banque des Territoires, d'après l'Institut pour la Ville et le Commerce","Vacance commerciale : les remèdes de l'Institut pour la Ville et le Commerce","s.d.",T_PRESSE,"https://www.banquedesterritoires.fr/vacance-commerciale-les-remedes-de-linstitut-pour-la-ville-et-le-commerce"),
 ("S21","Banque des Territoires","La progression de la vacance commerciale ralentit, surtout dans les villes moyennes","s.d. (données 2020-2022)",T_PRESSE,"https://www.banquedesterritoires.fr/la-progression-de-la-vacance-commerciale-ralentit-surtout-dans-les-villes-moyennes"),
 ("S22","Sénat, mission conjointe de contrôle","Revitalisation des centres-villes et des centres-bourgs : entre enthousiasme et frustrations, rapport d'information n° 910 (2021-2022)","2022",T_INST,"https://www.senat.fr/rap/r21-910/r21-9109.html"),
 ("S23","Cour des comptes","Synthèse sur les politiques publiques en faveur du commerce de proximité (intitulé exact à vérifier)","09/2023",T_INST,"https://www.ccomptes.fr/sites/default/files/2023-10/20230929-synthese-politiques-publiques-commerce-proximite.pdf"),
 ("S24","Cour des comptes","Rapport public annuel 2016, tome 2 : la politique de la ville","2016",T_INST,"https://www.ccomptes.fr/sites/default/files/EzPublish/07-politique-de-la-ville-RPA2016-Tome-2.pdf"),
 ("S25","Cour des comptes","L'évaluation de l'attractivité des quartiers prioritaires (rapport public thématique)","à préciser",T_INST,"https://www.ccomptes.fr/fr/publications/levaluation-de-lattractivite-des-quartiers-prioritaires"),
 ("S26","Cour des comptes (via AEF info, Journal des Arts, Courrier des maires)","Action Cœur de Ville : rapport sur la première phase du programme","09/2022",T_INST,"https://www.aefinfo.fr/depeche/679781-action-coeur-de-ville-un-programme-ambitieux-mais-difficile-a-evaluer-selon-la-cour-des-comptes"),
 ("S27","Mission sur l'avenir du commerce de proximité (rapport remis au Gouvernement)","Rapport sur l'avenir du commerce de proximité dans les centres-villes et les QPV","05/11/2025",T_INST,"https://www.banquedesterritoires.fr/sites/default/files/2025-11/Rapport-mission-commerce-de-proximite-centres-villes-QPVf.pdf"),
 ("S28","Direction générale des Entreprises","Mission sur l'avenir du commerce de proximité : neuf mesures retenues","11/2025",T_ADM,"https://www.entreprises.gouv.fr/la-dge/actualites/mission-sur-lavenir-du-commerce-de-proximite-neuf-mesures-retenues-pour"),
 ("S29","Sénat","Un nouveau pacte de solidarité pour les quartiers, rapport n° 49 (2006-2007)","2006",T_INST,"https://www.senat.fr/rap/r06-049-1/r06-049-1_mono.html"),
 ("S30","ONPV / ANCT","Comprendre le tissu économique en QPV : une hausse du nombre d'entreprises","2023",T_STAT,"https://www.onpv.fr/uploads/media_items/onpv-dossier-entreprises-2023.original.pdf"),
 ("S31","Observatoire des inégalités, d'après l'ONPV","Le chômage dans les quartiers prioritaires","s.d. (données 2022)",T_PRESSE,"https://www.inegalites.fr/Chomage-QPV"),
 ("S32","Observatoire des inégalités, d'après l'Insee","Les revenus et la pauvreté dans les quartiers les plus en difficulté","s.d. (données 2021)",T_PRESSE,"https://www.inegalites.fr/Les-revenus-et-la-pauvrete-dans-les-quartiers-les-plus-en-difficulte"),
 ("S33","ANCT","Quartiers prioritaires de la politique de la ville","2025",T_ADM,"https://anct.gouv.fr/quartiers-prioritaires"),
 ("S34","ANRU","Le commerce dans les quartiers prioritaires en renouvellement urbain","2025",T_ADM,"https://www.anru.fr/la-docutheque/le-commerce-dans-les-quartiers-prioritaires-en-renouvellement-urbain"),
 ("S35","ANCT","Action Cœur de Ville (pages programme et atlas)","2025",T_ADM,"https://anct.gouv.fr/programmes-dispositifs/action-coeur-de-ville"),
 ("S36","Banque des Territoires","Programme Action Cœur de Ville 2023-2026","s.d.",T_ADM,"https://www.banquedesterritoires.fr/programme-action-coeur-de-ville-2026"),
 ("S37","ANCT","Petites villes de demain : bilan au 31 décembre 2024","2025",T_ADM,"https://anct.gouv.fr/actualites/petites-villes-de-demain-3-ans-d-engagement-et-11-milliard-d-euros-investis"),
 ("S38","Banque des Territoires","La Banque des Territoires déploie un milliard d'euros pour soutenir le commerce","s.d.",T_ADM,"https://www.banquedesterritoires.fr/la-banque-des-territoires-deploie-un-milliard-deuros-pour-soutenir-le-commerce"),
 ("S39","Ministère de l'Économie / DGE","Plan de transformation des zones commerciales : annonce des lauréats","29/03/2024 et 24/05/2024",T_ADM,"https://www.entreprises.gouv.fr/la-direction-generale-des-entreprises/actualites/annonce-74-laureats-plan-transformation-zones-commerciales"),
 ("S40","Banque des Territoires","2023, année de transition de l'aménagement commercial ?","2024",T_PRESSE,"https://www.banquedesterritoires.fr/2023-annee-de-transition-de-lamenagement-commercial"),
 ("S41","CGDD / Cerema","Portail de l'artificialisation : consommation d'espaces naturels, agricoles et forestiers 2011-2025","2026",T_STAT,"https://artificialisation.developpement-durable.gouv.fr/actualites/parution-des-donnees-consommation-despaces-naturels-agricoles-et-forestiers-2011-2025"),
 ("S42","Cerema","Artificialisation des sols : quelle dynamique ? / données de consommation foncière 2009-2023","s.d.",T_ADM,"https://www.cerema.fr/fr/actualites/artificialisation-sols-quelle-dynamique"),
 ("S43","Assemblée nationale, commission du développement durable","Rapport d'information n° 4968 sur le rôle et l'avenir des commerces de proximité","26/01/2022",T_INST,"https://www.assemblee-nationale.fr/dyn/15/rapports/cion-dvp/l15b4968_rapport-information.pdf"),
 ("S44","LSA Conso","La périphérie urbaine aimante le commerce","s.d.",T_PRESSE,"https://www.lsa-conso.fr/la-peripherie-urbaine-aimante-le-commerce,323561"),
 ("S45","Légifrance","Lois n° 73-1193 (Royer), 96-603 (Raffarin), 2008-776 (LME), 2018-1021 (ELAN), 2021-1104 (Climat et résilience) ; décret du 13/10/2022","1973-2022",T_LOI,"https://www.legifrance.gouv.fr"),
 ("S46","EPARECA / LSA Conso ; CGET","L'Epareca aide les quartiers sensibles ; De nouvelles opérations pour le commerce et l'artisanat en QPV","s.d.",T_PRESSE,"https://www.lsa-conso.fr/l-epareca-aide-les-quartiers-sensibles,34533"),
 ("S47","ANCT","Dossier de presse, restructuration d'un centre commercial en QPV au Mans","10/2024",T_ADM,"https://media.anct.gouv.fr/s3fs-public/2024-10/DP_ANCT_LE%20MANS_2024_v4%20(7).pdf"),
 ("S48","Cour des comptes","Le développement des activités commerciales en centre-ville, rapport au ministre chargé du commerce (RPA 2026)","05/03/2026",T_INST,"https://www.vie-publique.fr/rapport/24822-le-developpement-des-activites-commerciales-en-centre-ville-rapport-au"),
 ("S49","IGF et IGEDD","La revitalisation commerciale des centres-villes","s.d.",T_INST,"https://www.igf.finances.gouv.fr/igf/accueil/nos-activites/rapports-de-missions/liste-de-tous-les-rapports-de-mi/la-revitalisation-commerciale-de.html"),
 ("S50","Bertrand M. et Kramarz F.","Does Entry Regulation Hinder Job Creation? Evidence from the French Retail Industry, Quarterly Journal of Economics, 117(4)","2002",T_ACAD,""),
 ("S51","Sadun R.","Does Planning Regulation Protect Independent Retailers?, Review of Economics and Statistics, 97(5)","2015",T_ACAD,""),
 ("S52","Quantin S. et Turner L. (Insee)","Le développement des grandes surfaces et son impact sur la durée de vie du petit commerce alimentaire de proximité, Journées de méthodologie statistique","2015",T_STAT,""),
 ("S53","Cour des comptes (RPA 2026, via synthèse)","Rapport public annuel 2026 : cohésion territoriale et attractivité des territoires","2026",T_INST,"https://www.ccomptes.fr/fr/publications/le-rapport-public-annuel-2026"),
]

# Chiffres : thème, indicateur, valeur, unité, années, territoire, périmètre, ref, vérif, remarque
TH1="1. Poids des zones commerciales périphériques"
TH2="2. Centres-villes : emploi et établissements"
TH3="3. Centres-villes : vacance commerciale"
TH4="4. Fréquentation, consommation, offre"
TH5="5. QPV : commerce et contexte"
TH6="6. Autorisations CDAC / CNAC"
TH7="7. Cadre réglementaire (seuils)"
TH8="8. Artificialisation et foncier"
TH9="9. Périphérie : vacance et transformation"
TH10="10. Politiques publiques : moyens et résultats"
TH11="11. Littérature économique : effets mesurés"

F = [
 # TH1
 (TH1,"Nombre de zones commerciales de périphérie",1500,"zones","2022-2023","France","Inventaire national du Cerema (photo-interprétation et fichiers fonciers). Ordre de grandeur : « 1 500 zones recensées ».","S01",V_A,""),
 (TH1,"Surface couverte par ces zones",500,"millions de m²","2022-2023","France","Emprise des zones (« cinq fois la superficie de Paris »). Ne correspond pas à la surface de vente : inclut vraisemblablement bâti, parkings et voiries.","S01",V_A,"Même chiffre dans le dossier de presse du Gouvernement (S08)."),
 (TH1,"Nombre de contours retenus dans la base EmpCom",1527,"contours","inventaire 2022, publié 02/2023","France métropolitaine","Emprises de plus de 20 000 m² de surface bâtie, et surface commerciale > 60 000 m² ou entre 25 000 et 150 000 m² avec > 15 000 m² de surface commerciale.","S02",V_A,"Base en open data (DataFoncier, data.gouv.fr)."),
 (TH1,"Part des déplacements en voiture vers les zones commerciales périphériques, métropoles",84,"%","s.d.","Métropoles","Part de la voiture individuelle dans les déplacements à destination des zones commerciales périphériques.","S01",V_A,"Source de l'enquête de mobilité non précisée sur la page."),
 (TH1,"Part des déplacements en voiture vers les zones commerciales périphériques, villes moyennes",88,"%","s.d.","Villes moyennes","Idem, villes moyennes.","S01",V_A,""),
 (TH1,"Part de la surface commerciale des pôles située dans les pôles de périphérie",65,"%","2015","France métropolitaine et La Réunion","Pôles du commerce de proximité au sens de l'Insee (commerce de détail + services de la vie courante). Les pôles de périphérie représentent 23 % des établissements des pôles.","S05",V_A,"Le résumé de la publication dit « deux tiers ». Ne pas citer 66 %."),
 (TH1,"Part de l'emploi salarié des pôles située dans les pôles de périphérie",45,"%","2015","France métropolitaine et La Réunion","Même champ (pôles du commerce de proximité).","S05",V_A,""),
 (TH1,"Nombre de pôles du commerce de proximité",7951,"pôles","2015","France métropolitaine et La Réunion","Pôles identifiés par l'Insee ; 62 % sont des pôles de périphérie.","S05",V_A,""),
 (TH1,"Part des salariés des points de vente aux ménages travaillant dans les pôles de périphérie",37,"%","2022","France","Points de vente aux ménages ; les pôles de centre-ville rassemblent aussi 37 % des salariés (1,0 million).","S07",V_A,"Champ et définition des pôles différents de l'Insee Première n° 1858."),
 (TH1,"Taille moyenne d'un point de vente en pôle de périphérie",586,"m² de surface de vente","2022","France","Moyenne par point de vente ; 12 salariés en moyenne ; 26 établissements par pôle en moyenne.","S07",V_A,""),
 (TH1,"Taille moyenne d'un point de vente en pôle de centre-ville",92,"m² de surface de vente","2022","France","Moyenne par point de vente ; 3 salariés en moyenne ; 108 établissements par pôle en moyenne.","S07",V_A,""),
 (TH1,"Part des dépenses des Français en magasin réalisées dans les entrées de ville / zones commerciales",72,"%","s.d. (dossier 2023)","France","Dépenses en magasin (hors internet). Centre-ville : 15 % ; espaces « interstices » (ruralité, banlieue dense) : 13 %.","S08",V_A,"La source statistique d'origine n'est pas donnée (renvoi en note non détaillé). Aussi relayé par LSA Conso (S44)."),
 (TH1,"Part des dépenses en magasin réalisées en centre-ville",15,"%","s.d. (dossier 2023)","France","Même champ que la ligne précédente.","S08",V_A,""),
 (TH1,"Part du chiffre d'affaires du commerce de détail réalisée dans les lieux de commerce de périphérie",70,"% (plus de)","s.d. (dossier 2025)","France","Chiffre d'affaires du commerce de détail, selon Procos.","S09",V_A,"Formulé « plus de 70 % » sans détail de méthode."),
 (TH1,"Part de marché du commerce de détail des quelque 1 500 zones commerciales",75,"%","2020","France","Parts de marché du commerce de détail (source Procos, 2020, citée par le Cerema).","S03",V_C,"Lu sur la page Cerema ; la publication Procos d'origine n'a pas été consultée."),
 (TH1,"Part des ventes du commerce de détail réalisées en périphérie",67,"%","2024","France","Ensemble des ventes du commerce de détail, internet compris.","S13",V_E,"Répartition : périphérie 67 %, centre-ville 11 %, proximité 11 %, internet 11 %."),
 (TH1,"Part des ventes du commerce de détail réalisées en centre-ville",11,"%","2024","France","Même champ (internet compris).","S13",V_E,""),
 (TH1,"Part des ventes du commerce de détail réalisées sur internet",11,"%","2024","France","Même champ.","S13",V_E,""),
 (TH1,"Évolution des surfaces commerciales entre 2000 et 2020","x 2","multiplicateur","2000-2020","France","Doublement des surfaces commerciales sans hausse équivalente des dépenses des ménages (« obésité commerciale »).","S22",V_B,""),
 (TH1,"Distance moyenne entre zones commerciales et centre-ville",3.2,"km","s.d.","France","Distance moyenne des plus de 1 500 zones aux centres-villes.","S44",V_D,"Article de presse ; méthode et source d'origine non identifiées."),
 # TH2
 (TH2,"Croissance annuelle de l'emploi salarié dans les pôles de périphérie",2.3,"% par an","2009-2015","France métropolitaine et La Réunion","Emploi salarié du commerce de proximité dans les pôles de périphérie.","S05",V_A,""),
 (TH2,"Croissance annuelle de l'emploi salarié dans les pôles de centre-ville",0.2,"% par an","2009-2015","France métropolitaine et La Réunion","Même champ, pôles de centre-ville (« stabilité »).","S05",V_A,"La note du CAE (S12) écrit « a baissé de 0,2 % » : l'Insee indique +0,2 %."),
 (TH2,"Évolution annuelle de l'emploi du commerce de proximité hors pôles",-1.2,"% par an","2009-2015","France métropolitaine et La Réunion","Commerces isolés, hors pôles commerciaux.","S05",V_A,""),
 (TH2,"Part des pôles de centre-ville où l'emploi salarié baisse",38,"%","2009-2015","France métropolitaine et La Réunion","Contre 23 % des pôles de périphérie.","S05",V_A,""),
 (TH2,"Part des pôles de périphérie où l'emploi salarié baisse",23,"%","2009-2015","France métropolitaine et La Réunion","","S05",V_A,""),
 (TH2,"EPCI où l'emploi des pôles de périphérie croît de plus de 1 %/an : part où l'emploi des centres-villes baisse de plus de 1 %/an",46,"%","2009-2015","France métropolitaine et La Réunion","Croisement par EPCI de l'évolution de l'emploi des pôles de périphérie et de centre-ville.","S05",V_A,"Quand la périphérie recule d'au moins 1 %/an, la part est de 43 %."),
 (TH2,"Pôles de centre-ville en baisse d'emploi dans les aires en recul démographique",57,"%","2009-2015","France métropolitaine et La Réunion","Pôles où l'emploi salarié « se replie nettement » ; 30 % dans les aires les plus dynamiques.","S05",V_A,"Pour les pôles de périphérie : 27 % contre 18 %."),
 (TH2,"Part des centres-villes de villes de taille intermédiaire (VTI) en baisse tendancielle d'emploi",82,"%","2009-2015","368 villes de taille intermédiaire","Emploi salarié du commerce de proximité en centre-ville.","S06",V_A,"Dans la moitié des VTI, la baisse dépasse 1,4 % par an."),
 (TH2,"Établissements détruits chaque année dans les centres-villes des VTI",600,"établissements par an","2009-2015","368 VTI","Commerce de proximité, centres-villes.","S06",V_A,"Dans le même temps, les agglomérations gagnent 100 établissements par an."),
 (TH2,"Emplois salariés détruits chaque année dans les centres-villes des VTI",3500,"emplois par an","2009-2015","368 VTI","Commerce de proximité, centres-villes.","S06",V_A,"Dans le même temps, les agglomérations gagnent 1 600 salariés par an."),
 (TH2,"Part des VTI où l'emploi baisse en centre-ville mais augmente dans l'agglomération",37,"%","2009-2015","368 VTI","","S06",V_A,""),
 (TH2,"Croissance annuelle de l'emploi salarié des points de vente, pôles de centre-ville",1.1,"% par an","2016-2022","France","Points de vente aux ménages (commerce de détail, restauration, services).","S07",V_A,"+1,0 % hors bassin de vie de Paris."),
 (TH2,"Croissance annuelle de l'emploi salarié des points de vente, pôles de périphérie",1.6,"% par an","2016-2022","France","Même champ. Nombre d'établissements +1,7 %/an, surface de vente +1,3 %/an.","S07",V_A,""),
 (TH2,"Croissance annuelle de l'emploi salarié des points de vente hors pôles",1.9,"% par an","2016-2022","France","Même champ.","S07",V_A,""),
 (TH2,"Contribution des pôles de périphérie à la hausse de l'emploi salarié des points de vente",40,"%","2016-2022","France","Hausse totale : +235 000 salariés (+1,5 %/an). Contribution des pôles de centre-ville : 28 %.","S07",V_A,""),
 (TH2,"Évolution annuelle de l'emploi salarié dans le commerce de détail d'habillement",-2.2,"% par an","2016-2022","France","Ensemble des points de vente. Nombre d'établissements d'habillement : −14,9 % sur la période.","S07",V_A,"Équipement de la personne hors biens médicaux : −1,6 %/an."),
 (TH2,"Nombre d'établissements du petit commerce",430000,"établissements","2019","France","Petit commerce au sens large du CAE (commerce de détail hors grandes surfaces, bars, restaurants, services aux ménages) ; environ 12 % de l'emploi total et 6 % du PIB.","S12",V_A,""),
 # TH3
 (TH3,"Taux de vacance commerciale en centre-ville",6,"%","2001","187 centres-villes (panel CGEDD)","Vacance commerciale, panel de 187 centres-villes.","S18",V_C,"Rapport CGEDD (2016) cité par Public Sénat ; plus de 10 % en 2015 sur le même panel."),
 (TH3,"Taux de vacance commerciale en centre-ville",10,"% (plus de)","2015","187 centres-villes (panel CGEDD)","Idem.","S18",V_C,""),
 (TH3,"Part des centres-villes où la vacance augmente",87,"%","période d'étude du rapport (avant 2016)","900 centres-villes","Rapport interministériel CGEDD / IGF.","S19",V_C,"Cité par le Cerema selon nos notes ; la mention n'a pas été retrouvée sur la page consultée en 10/2026."),
 (TH3,"Taux de vacance commerciale en centre-ville",11.3,"%","2016","Centres-villes des agglomérations de plus de 25 000 habitants","Selon l'Institut pour la Ville et le Commerce ; hausse d'environ 1 point par an depuis 2010.","S20",V_C,""),
 (TH3,"Taux de vacance dans les centres-villes Action Cœur de Ville",13,"%","2020","Villes ACV","+1 point par rapport à 2019.","S22",V_B,""),
 (TH3,"Taux de vacance commerciale tous sites",10.64,"%","2024","France","Codata Digest France (janvier 2025) : rues marchandes, centres commerciaux et zones commerciales. 9,73 % en 2023.","S09",V_A,"La mission de 2025 (S27) attribue 10,64 % aux seuls centres-villes."),
 (TH3,"Taux de vacance dans les rues marchandes (pied d'immeuble)",10.85,"%","2024","France","Codata ; 9,73 % en 2023.","S09",V_A,"Panel de 4 045 sites selon L'Échommerces (S15)."),
 (TH3,"Taux de vacance en pied d'immeuble de centre-ville",11.7,"%","2025","France","Codata Digest 2026 ; 10,8 % en 2024.","S14",V_E,""),
 (TH3,"Taux de vacance commerciale en centre-ville",11,"%","2022 (chiffres Procos)","France","Valeur donnée « par exemple » pour comparer avec les zones commerciales (9 %).","S08",V_A,""),
 (TH3,"Taux de vacance commerciale national",14,"%","2024","France","« Doublé en dix ans » ; aussi formulé comme le passage de 6 % (2010) à 14 % (2024) dans les centres-villes.","S27",V_C,"Lu dans des synthèses du rapport ; champ exact à vérifier dans le rapport."),
 (TH3,"Part des boutiques fermées en centre-ville","1 sur 10","ratio","2025","France","Formulation du communiqué de la DGE sur la mission.","S28",V_B,""),
 (TH3,"Taux de vacance dans les villes Action Cœur de Ville",13.4,"%","2024","Villes ACV","Baromètre Codata / FACT ; 7,7 % hors ACV.","S17",V_C,""),
 (TH3,"Taux de vacance commerciale moyen, toutes communes",9.67,"%","2024","France","Baromètre Codata / FACT ; 9,22 % en 2022.","S17",V_C,""),
 (TH3,"Taux de vacance dans les villes Action Cœur de Ville",12.5,"%","2022","Villes ACV","Étude Codata / FACT ; 7,39 % dans un groupe de comparaison hors ACV.","S16",V_C,"Baisse de 1,7 point depuis le pic de 2020 (−0,3 point hors ACV)."),
 (TH3,"Taux de vacance à Vierzon",28.8,"%","2018","Vierzon (centre-ville)","22,2 % en 2022.","S16",V_C,""),
 (TH3,"Taux de vacance à Calais",21.5,"% (21,3 à 21,7)","2018","Calais (centre-ville)","14 % en 2022.","S16",V_C,""),
 (TH3,"Taux de vacance à Bagnols-sur-Cèze",21.3,"%","2018","Bagnols-sur-Cèze (centre-ville)","14,3 % en 2022.","S16",V_C,""),
 (TH3,"Taux de vacance en cœur de métropole",8.3,"%","s.d. (vers 2020-2022)","Métropoles de plus de 700 000 habitants","Passé de 7,6 % à 8,3 %, jamais au-dessus de 9 %.","S21",V_C,""),
 (TH3,"Taux de vacance dans les grandes villes",11,"% (environ)","s.d. (vers 2020-2022)","Villes de 200 000 à 700 000 habitants","Stagnation.","S21",V_C,""),
 (TH3,"Taux de vacance dans les villes moyennes",12.6,"%","2022","Bassins de 50 000 à 200 000 habitants","13,6 % en 2020.","S21",V_C,""),
 (TH3,"Taux de vacance dans les petites villes",12,"%","2022","Bassins de moins de 50 000 habitants","13,1 % en 2020.","S21",V_C,""),
 (TH3,"Taux de vacance par région, le plus élevé (Occitanie)",12.46,"%","2024","Occitanie","Codata. Le plus faible : Bretagne, 8,92 %.","S09",V_A,""),
 (TH3,"Taux de vacance commerciale tous formats",11.6,"%","2025","France","10,7 % en 2024.","S53",V_D,"Chiffre lu dans une synthèse automatique du RPA 2026 ; à vérifier dans le rapport."),
 # TH4
 (TH4,"Évolution de la fréquentation des magasins en centre-ville",-1.8,"% sur un an","2024 vs 2023","France","Observatoire de la fréquentation Procos / Stackr.","S09",V_A,"Périphérie −1,2 % ; centres commerciaux −0,8 % ; ensemble −1,6 %."),
 (TH4,"Évolution de la fréquentation des magasins en périphérie",-1.2,"% sur un an","2024 vs 2023","France","Idem.","S09",V_A,""),
 (TH4,"Évolution de la fréquentation des magasins, ensemble",-1.6,"% sur un an","2024 vs 2023","France","Idem ; −2,3 % en 2023 selon nos notes.","S09",V_A,""),
 (TH4,"Part de marché du commerce alimentaire de proximité",17,"%","2017","France","22 % en 1993.","S23",V_B,""),
 (TH4,"Poids de l'équipement de la personne dans l'offre de certains centres-villes","40 à 60","%","s.d.","Certains centres-villes","Surreprésentation de l'habillement et des accessoires.","S22",V_B,""),
 (TH4,"Part de l'habillement dans l'offre en pied d'immeuble",15.05,"%","2024","France","20,92 % en 2015. Les cafés-hôtels-restaurants montent à 21,67 % de l'offre.","S15",V_C,""),
 (TH4,"Établissements perdus par l'équipement de la personne en dix ans",14000,"établissements","environ 2016-2026","France","Équipement de la personne.","S11",V_C,"Lu dans le baromètre Icade, qui cite la revue Urbanisme n° 448 (avril 2026)."),
 (TH4,"Part du e-commerce dans le commerce de détail",14.1,"%","2021","France","Estimation Fevad citée par le CAE ; 129 milliards d'euros dépensés en ligne en 2021 (biens et services).","S12",V_A,""),
 # TH5
 (TH5,"Nombre de QPV en métropole",1362,"quartiers","01/01/2025","France métropolitaine","Géographie prioritaire 2024 ; 156 dans les DROM et 91 en Polynésie et à Saint-Martin.","S33",V_B,""),
 (TH5,"Population des QPV",6,"millions d'habitants (plus de)","2025","France","","S33",V_B,""),
 (TH5,"Taux de chômage en QPV",18.3,"%","2022","QPV","7,5 % dans les unités urbaines englobantes ; 25 % en 2014.","S31",V_C,"Moins de 30 ans : 26 % contre 13,5 %."),
 (TH5,"Taux de pauvreté en QPV",45,"%","2021","QPV","2,5 fois le taux des villes qui les abritent.","S32",V_C,""),
 (TH5,"Niveau de vie médian en QPV",1213,"€ par mois","2021","QPV","1 900 € dans le reste des agglomérations englobantes.","S32",V_C,""),
 (TH5,"Évolution du nombre d'entreprises en QPV","x 2 (presque)","multiplicateur","5 ans avant 2023","QPV","Toutes entreprises ; secteurs les plus représentés : commerce, transport, construction.","S30",V_B,""),
 (TH5,"Part du commerce de détail dans les établissements des QPV",15.8,"%","01/01/2021","QPV de métropole","18,2 % dans les QPV des DROM.","S30",V_B,""),
 (TH5,"Part du commerce de détail dans les créations d'établissements en QPV",9.2,"%","2021","QPV de métropole","Sur 92 590 nouveaux établissements.","S30",V_B,""),
 (TH5,"Opérations ANRU consacrées au commerce de proximité",122,"opérations","s.d. (NPNRU)","QPV en renouvellement urbain","Dotation ANRU de 322 M€ et cofinancement de 67 M€.","S34",V_B,""),
 (TH5,"Centres commerciaux ou pôles artisanaux restructurés par l'EPARECA",50,"(plus de)","depuis 2001","QPV","Opérateur public créé en 1996, intégré depuis à l'ANCT.","S46",V_C,""),
 (TH5,"Coût d'une restructuration de centre commercial en QPV (Le Mans)",4212100,"€","2023-2025","Le Mans","Financement : Le Mans Métropole 1 254 750 €, ANCT 1 203 491 €, ANRU 1 058 131 €, FRLA 695 728 €.","S47",V_B,""),
 # TH6
 (TH6,"Surface de vente autorisée par les CDAC",583466,"m²","2020","France","Autorisations et avis favorables des CDAC (tableau 1).","S10",V_A,""),
 (TH6,"Surface de vente autorisée par les CDAC",688220,"m²","2021","France","Idem.","S10",V_A,""),
 (TH6,"Surface de vente autorisée par les CDAC",765384,"m²","2022","France","Idem.","S10",V_A,""),
 (TH6,"Surface de vente autorisée par les CDAC",625386,"m²","2023","France","Idem.","S10",V_A,""),
 (TH6,"Surface de vente autorisée par les CDAC",605844,"m²","2024","France","Idem ; 338 autorisations, taux d'autorisation 88 %.","S10",V_A,""),
 (TH6,"Surface de vente examinée par les CDAC",685215,"m²","2024","France","Autorisations + refus (384 dossiers) ; 878 373 m² en 2022.","S10",V_A,""),
 (TH6,"Surface de vente examinée par la CNAC",234940,"m²","2024","France","487 999 m² en 2023 (−52 %) ; 145 avis ou décisions contre 181.","S10",V_A,"Surface moyenne examinée : 1 620 m² (2 696 m² en 2023)."),
 (TH6,"Surface de vente autorisée par la CNAC",138031,"m²","2024","France","318 032 m² en 2023 (tableau 2).","S10",V_A,""),
 (TH6,"Projets examinés par la CNAC susceptibles d'artificialiser les sols",29,"dossiers","2024","France","Pour 199 045 m² (117 625 m² en 2023). 12 autorisés (115 375 m²), 17 refusés (83 668 m²).","S10",V_A,""),
 (TH6,"Surface désartificialisée par les projets autorisés en CNAC",37127,"m²","2024","France","31 dossiers proposant une désartificialisation volontaire et ayant reçu un avis favorable.","S10",V_A,""),
 (TH6,"Surfaces autorisées en CDAC (série Kyris / Procos)",1.31,"millions de m²","2019","France","Hors retraits de dossiers et non-lieux. 703 dossiers autorisés sur 813.","S09",V_A,"Champ différent du rapport CNAC (S10)."),
 (TH6,"Surfaces autorisées en CDAC (série Kyris / Procos)",0.47,"millions de m²","2024","France","Idem ; 355 dossiers autorisés sur 406 ; « −67 % depuis 2019, 7 fois moins qu'en 2011 ».","S09",V_A,"Série 2020-2023 : 0,62 / 0,55 / 0,82 / 0,72."),
 (TH6,"Surface moyenne des dossiers autorisés en CDAC",1320,"m² de surface de vente","2024","France","Série Kyris / Procos.","S09",V_A,"Surface moyenne des projets en stock : 5 000 m² (14 000 m² en 2014)."),
 (TH6,"Surfaces de plancher commercial autorisées (permis de construire)",3.9,"millions de m²","2024","France","Sitadel2 (toutes autorisations de surfaces commerciales, pas seulement CDAC) ; 4,1 en 2023, 4,4 en 2022.","S09",V_A,"Surfaces commencées : 2,2 millions de m² en 2024."),
 (TH6,"Surfaces de vente terminées (projets des grands promoteurs) sur 5 ans",1774501,"m²","2020-2024","France","376 projets (4 720 m² en moyenne), hors alimentaire, restauration et loisirs ; 5,4 millions de m² et 518 projets cinq ans plus tôt.","S09",V_A,""),
 (TH6,"Surface examinée en CDAC",1700000,"m² (environ)","2017","France","996 projets examinés, 643 autorisés.","S40",V_C,""),
 (TH6,"Surface autorisée en CDAC",557000,"m² (environ)","2023","France","Taux d'approbation de 86 %.","S40",V_C,"Diffère du tableau 1 du rapport CNAC (625 386 m²) : périmètres à comparer."),
 (TH6,"Surface dont l'artificialisation a été évitée par des refus de la CNAC",89870,"m²","2023","France","29 projets rejetés, effet attribué au décret du 13 octobre 2022.","S40",V_C,""),
 # TH7
 (TH7,"Seuil d'autorisation commerciale, loi Royer",1000,"m² (1 500 m² dans les villes > 40 000 hab.)","1973","France","Surface de vente au-delà de laquelle une autorisation est requise.","S45",V_C,"Vérifier sur Légifrance (loi n° 73-1193)."),
 (TH7,"Seuil d'autorisation commerciale, loi Raffarin",300,"m²","1996","France","Abaissement du seuil.","S45",V_C,"Loi n° 96-603."),
 (TH7,"Seuil d'autorisation commerciale, loi LME",1000,"m²","2008","France","Relèvement du seuil ; création des CDAC.","S45",V_C,"Loi n° 2008-776."),
 (TH7,"Durée de suspension possible des projets en périphérie d'une ORT (loi ELAN, art. 157)",3,"ans (+1 renouvelable)","2018 (application 07/2019)","Communes en ORT","Le préfet peut suspendre l'examen en CDAC des projets situés hors des périmètres de l'ORT.","S45",V_C,"Loi n° 2018-1021 ; décret du 26 juillet 2019."),
 (TH7,"Seuil au-delà duquel aucune dérogation n'est possible pour un projet artificialisant (loi Climat et résilience)",10000,"m² de surface de vente","2021","France","Art. 215 ; entre 3 000 et 10 000 m², dérogation soumise à l'accord du préfet.","S45",V_C,"Loi n° 2021-1104."),
 (TH7,"Date d'obligation d'examen du critère d'artificialisation par les commissions",2022,"année (15 octobre)","2022","France","Décret d'application du 13 octobre 2022.","S10",V_A,""),
 # TH8
 (TH8,"Consommation d'espaces naturels, agricoles et forestiers",15119,"ha","2024","France","Tous usages ; plus bas niveau depuis le début du suivi (2011).","S41",V_B,""),
 (TH8,"Consommation moyenne annuelle d'espaces naturels, agricoles et forestiers",24315,"ha par an","2009-2023","France (DOM compris)","Cerema, rapport « Analyse de la consommation d'espaces », mai 2024.","S10",V_A,"Cité dans le rapport CNAC 2024."),
 (TH8,"Surface artificialisée",19263,"ha","2023","France","Tous usages ; 63 % habitat, 23 % activité économique (commerce compris).","S42",V_C,""),
 (TH8,"Part de l'activité économique dans l'artificialisation",25,"%","2009-2018","France","Activité économique (industrie, commerce, etc.) ; habitat 68 %.","S42",V_B,"Pas de décomposition propre au commerce."),
 (TH8,"Sites commerciaux EmpCom comportant au moins une friche",123,"sites","2024","France","Soit 7 % des sites à vocation commerciale ; environ 10 % de leur surface en friche (409 ha).","S04",V_A,""),
 # TH9
 (TH9,"Taux de vacance dans les zones commerciales",4,"% (moins de)","2007","France","Zones commerciales de périphérie.","S03",V_A,"« Aurait doublé » : plus de 8 % en 2020. Source d'origine non précisée par le Cerema."),
 (TH9,"Taux de vacance dans les zones commerciales",8,"% (plus de)","2020","France","Idem.","S03",V_A,""),
 (TH9,"Taux de vacance dans les zones commerciales",9,"%","2022 (chiffres Procos)","France","Comparé à 11 % en centre-ville.","S08",V_A,""),
 (TH9,"Taux de vacance dans les zones commerciales (Codata)",7.24,"%","2024","France","Codata ; 6,79 % en 2023.","S09",V_A,""),
 (TH9,"Taux de vacance dans les 60 plus grandes zones commerciales",4,"%","2024","France","« Vacance quasi absente ».","S09",V_A,""),
 (TH9,"Taux de vacance dans les centres commerciaux (Codata)",16.7,"%","2024","France","14,95 % en 2023.","S09",V_A,"L'Échommerces (S15) donne 16,04 % pour 2024."),
 (TH9,"Taux de vacance dans les zones commerciales (Codata)",8.4,"%","2025","France","6,9 % en 2022 ; centres commerciaux 16,8 % en 2025.","S14",V_E,""),
 (TH9,"Taux de vacance des zones commerciales (FACT)",6.9,"%","2021","France","Série FACT reproduite dans le baromètre.","S11",V_C,"Lu dans le baromètre Icade × SCET, qui cite la FACT."),
 (TH9,"Taux de vacance des zones commerciales (FACT)",6.9,"%","2022","France","Idem.","S11",V_C,""),
 (TH9,"Taux de vacance des zones commerciales (FACT)",7.4,"%","2023","France","Idem.","S11",V_C,""),
 (TH9,"Taux de vacance des zones commerciales (FACT)",8.1,"%","2024","France","Idem.","S11",V_C,""),
 (TH9,"Taux de vacance des zones commerciales (FACT)",8.4,"%","2025","France","Idem.","S11",V_C,""),
 (TH9,"Taux de vacance des zones commerciales (FACT)",8.5,"%","2026","France","Idem ; « se creuse depuis 2022 ».","S11",V_C,""),
 (TH9,"Projets de transformation d'entrées de ville recensés",437,"projets","2026","France métropolitaine","Recensement Icade × SCET (non exhaustif) ; 8 606 ha au total.","S11",V_A,""),
 (TH9,"Part des projets au stade de l'intention",56,"%","2026","France métropolitaine","34 % à l'étude, 5 % en recyclage foncier, 3 % en travaux, 1 % achevés.","S11",V_A,""),
 (TH9,"Part des projets portés par des acteurs privés",66,"%","2026","France métropolitaine","","S11",V_A,"53 % des sites font moins de 3 ha."),
 (TH9,"Part des élus jugeant les entrées de ville stratégiques",93,"%","juin-juillet 2026","Communes de plus de 10 000 habitants","Sondage Quorum auprès de 1 000 élus locaux.","S11",V_A,"53 % citent le frein financier, 43 % le frein réglementaire."),
 (TH9,"Sites d'entrée de ville identifiés (1re édition du baromètre)",3838,"sites","2025","France","80 000 ha ; potentiel annoncé de 1,6 million de logements.","S11",V_A,"Rappel de la 1re édition dans la 2e."),
 # TH10
 (TH10,"Villes ou binômes retenus dans Action Cœur de Ville",222,"villes ou binômes","26/03/2018","France","Lancement du programme.","S35",V_B,"La Cour des comptes parle de 234 villes moyennes dans 222 territoires."),
 (TH10,"Communes lauréates d'Action Cœur de Ville",244,"communes","2025","France (dont une dizaine en outre-mer)","","S35",V_B,""),
 (TH10,"Montants mobilisés par Action Cœur de Ville, phase 1",6,"milliards d'euros (plus de)","2018-2022","Villes ACV","Ensemble des partenaires.","S35",V_B,""),
 (TH10,"Enveloppe Action Cœur de Ville, phase 2",5,"milliards d'euros","2023-2026","Villes ACV","Accent sur les entrées de ville et les quartiers de gare.","S36",V_B,""),
 (TH10,"Commerces et locaux d'activité restructurés (ACV)",29000,"locaux (près de)","2018-2025","Villes ACV","Résultat cumulé annoncé par l'ANCT.","S35",V_B,""),
 (TH10,"Évolution de la fréquentation des villes ACV",15,"%","2021","Villes ACV","+2 % dans les centres-villes hors ACV.","S26",V_C,""),
 (TH10,"Évolution des transactions immobilières dans les villes ACV",14,"%","2018-2021","Villes ACV","Par rapport à 2018.","S26",V_C,""),
 (TH10,"Emplois soutenus par les investissements ACV",10100,"emplois","2018-2020","Villes ACV","857 M€ d'investissement générés par 335,8 M€ de financements ACV.","S22",V_B,""),
 (TH10,"Communes bénéficiant de Petites villes de demain",1646,"communes","31/12/2024","Communes de moins de 20 000 habitants","Plus de 7 millions de personnes concernées.","S37",V_B,""),
 (TH10,"Financements engagés dans Petites villes de demain",3.7,"milliards d'euros","au 31/12/2024","Communes PVD","3 milliards prévus ; effet de levier de l'État estimé entre 4 et 5.","S37",V_B,""),
 (TH10,"Plan commerce de la Banque des Territoires",1,"milliard d'euros","s.d.","France","Dont 800 M€ pour les foncières de redynamisation (300 M€ en fonds propres, 500 M€ en prêts).","S38",V_B,""),
 (TH10,"Objectif de commerces remis sur le marché par les foncières",6000,"commerces","s.d.","France","Objectif d'une centaine de foncières.","S38",V_B,""),
 (TH10,"Projets soutenus par le plan de transformation des zones commerciales",90,"projets","2024","France","74 lauréats en mars 2024 (26 M€, dont 20,3 M€ de travaux) et 16 en mai 2024 (5,4 M€) ; 31,4 M€ au total.","S39",V_E,"Potentiel annoncé : 25 000 logements pour les 74 premiers projets."),
 (TH10,"Recommandations de la mission sur l'avenir du commerce de proximité",30,"recommandations","2025","Centres-villes et QPV","Cinq axes ; neuf mesures retenues par le Gouvernement.","S28",V_B,""),
 (TH10,"Mesures proposées par le Sénat (rapport n° 910)",43,"mesures","2022","France","Cinq priorités, dont un objectif de « zéro artificialisation commerciale nette » en périphérie.","S22",V_B,""),
 # TH11
 (TH11,"Petits commerces alimentaires de centre-ville disparus dans les 4 ans suivant l'entrée d'une grande surface","20 à 30","%","étude citée par le CAE","Espagne","75 % des emplacements libérés sont repris par d'autres petits commerces, non alimentaires.","S12",V_C,"Étude espagnole citée par la note du CAE ; référence d'origine non relue."),
 (TH11,"Emplois créés dans le commerce de détail l'année suivant l'ouverture d'un Walmart",100,"emplois","études citées par le CAE","États-Unis (comté)","La moitié a disparu au bout de cinq ans ; sortie nette de 4 établissements en cinq ans ; pas d'effet mesurable dans les comtés voisins.","S12",V_C,"Littérature américaine citée par le CAE."),
]

GAPS = [
 # catégorie, besoin, donnée, détenteur, apport, accès, statut, priorité, démarche
 ("Données statistiques","Mesurer l'offre en surfaces, pas seulement en nombre d'établissements","Surfaces de vente par établissement (fichier de la taxe sur les surfaces commerciales, TASCOM)","DGFiP ; DGE","Pondérer chaque commerce par sa surface ; suivre l'ouverture des grandes surfaces dans le temps","Non ouvert : demande à la DGFiP ou à la DGE","Manquant","Haute","Demander à la DGE (bureau du commerce) l'accès à une extraction anonymisée par commune"),
 ("Données statistiques","Identifier les ouvertures de surfaces en périphérie projet par projet","Base consolidée des décisions CDAC / CNAC (date, adresse, surface, enseigne, autorisation ou refus)","DGE (secrétariat de la CNAC) ; préfectures","Comparer les territoires où un projet a été autorisé et ceux où il a été refusé (approche quasi expérimentale)","Décisions publiées une à une ; pas de base ouverte consolidée","Manquant","Haute","Demander la base nationale à la DGE ; à défaut, Kyris / Procos (payant)"),
 ("Données statistiques","Mesurer la vacance commerciale au niveau local","Locaux d'activité vacants (fichiers fonciers, base LOCOMVAC du Cerema) ; relevés de terrain Codata","Cerema (fichiers fonciers) ; Codata (privé)","Mesurer directement la vacance en centre-ville et en QPV, au lieu du nombre d'établissements","Fichiers fonciers : convention réservée aux acteurs publics et chercheurs ; Codata : payant","Manquant","Haute","Demander l'accès aux fichiers fonciers via le Cerema (DataFoncier) ; outil de diagnostic de la vacance annoncé par la mission de 2025"),
 ("Données statistiques","Mesurer l'activité réelle (chiffre d'affaires, dépenses)","Dépenses par carte bancaire localisées (lieu d'achat et lieu de résidence)","Groupements bancaires (CB, Crédit Mutuel Alliance Fédérale…) ; Insee en partenariat","Savoir où consomment les habitants des centres et des QPV, et ce que la périphérie capte","Accès par partenariat de recherche","Manquant","Haute","S'inspirer de l'Insee Première n° 2075 (achats frontaliers) qui utilise ces données"),
 ("Données statistiques","Mesurer l'emploi salarié par établissement","Base tous salariés / DSN ; FLORES","Insee","Remplacer le critère employeur oui/non par les effectifs ; reproduire les pôles de l'Insee","Accès sécurisé (CASD) sur projet","Partiel (Sirene donne seulement le caractère employeur)","Moyenne","Déposer une demande CASD, ou demander des tableaux à façon à l'Insee"),
 ("Données statistiques","Disposer de la géographie des pôles commerciaux de l'Insee","Pôles du commerce de proximité (Insee Première n° 1858 et 2091)","Insee","Comparer directement nos zones (Cerema) avec les pôles de périphérie et de centre-ville de l'Insee","Fichiers de données des publications partiellement en ligne ; contours non publiés","Manquant","Moyenne","Récupérer les fichiers xlsx des publications ; demander les contours à l'Insee"),
 ("Données statistiques","Suivre la date de création des zones et leurs extensions","Historique des contours des zones commerciales ; dates de construction des locaux (fichiers fonciers)","Cerema","EmpCom est figée en 2021 : impossible de dater l'arrivée d'une zone près d'un centre","Fichiers fonciers sous convention","Manquant","Haute","Reconstituer les dates via les fichiers fonciers ou Sitadel"),
 ("Données statistiques","Mesurer les flux de clients","Fréquentation piétonne et flux de mobilité (comptages, données de téléphonie)","Procos / Stackr, MyTraffic, Orange Flux Vision (privés)","Mesurer la fréquentation des centres et des QPV avant et après l'ouverture d'une zone","Payant","Manquant","Moyenne","Partenariat ponctuel sur quelques villes tests"),
 ("Données statistiques","Comprendre les déplacements d'achat des habitants des QPV","Enquêtes mobilité (EMP 2019, enquêtes ménages-déplacements locales)","SDES / Insee ; Cerema et autorités organisatrices","Mesurer la part des achats des habitants de QPV réalisés en périphérie","Fichiers détail via ADISP / CASD ; enquêtes locales sur demande","Manquant","Moyenne","Exploiter les enquêtes ménages-déplacements des grandes agglomérations"),
 ("Données statistiques","Contrôler le pouvoir d'achat local","Revenus carroyés (Filosofi), revenus par QPV","Insee","Isoler l'effet du revenu, que la Cour des comptes cite comme première cause","Ouvert","Disponible, non intégré à notre analyse","Moyenne","Ajouter Filosofi aux modèles"),
 ("Données statistiques","Suivre les surfaces commerciales construites","Sitadel (permis de construire, locaux commerciaux autorisés et commencés)","SDES","Mesurer la construction commerciale par commune et par année","Ouvert","Disponible, non intégré","Moyenne","Télécharger les séries communales de locaux d'activité"),
 ("Données statistiques","Suivre les grands magasins et leurs dates d'ouverture","Base permanente des équipements (hypermarchés, supermarchés, grandes surfaces spécialisées) ; bases de points de vente (LSA Expert, Nielsen)","Insee (BPE, ouverte) ; LSA, Nielsen (payant)","Repérer les ouvertures de grandes surfaces avec leur format","BPE ouverte ; bases privées payantes","Partiel","Moyenne","Croiser la BPE annuelle avec Sirene"),
 ("Données statistiques","Évaluer l'effet des politiques publiques","Listes et dates des communes en ORT, ACV, PVD, lauréats du plan zones commerciales ; périmètres d'ORT","ANCT ; DGE","Distinguer l'effet de la périphérie de celui des programmes de revitalisation","Listes ACV / PVD ouvertes ; périmètres ORT à vérifier","Partiel","Haute","Récupérer les listes sur data.gouv.fr et les dates de signature des conventions"),
 ("Données statistiques","Mesurer les loyers et la valeur des locaux","Loyers commerciaux, valeurs locatives des locaux professionnels, transactions (DVF)","DGFiP (valeurs locatives, DVF) ; observatoires privés","Voir si la périphérie fait baisser les loyers en centre","DVF ouvert ; valeurs locatives par secteur publiées ; loyers privés payants","Manquant","Basse","Commencer par DVF (ventes de locaux commerciaux)"),
 ("Données statistiques","Mesurer la vacance spécifique aux QPV","Indicateur consolidé de vacance commerciale en QPV","ONPV / ANCT ; ANRU","Aucun indicateur national n'existe aujourd'hui","Inexistant","Manquant","Haute","Signaler le manque ; s'appuyer sur les diagnostics ANRU"),
 ("Données statistiques","Disposer de données comparables en Europe","Données harmonisées sur la localisation du commerce (centre / périphérie) dans les pays de l'UE","Eurostat ; JRC ; offices statistiques nationaux","Comparer la France aux autres pays européens","Pas de base harmonisée identifiée","Manquant","Basse","Recenser les études nationales (Royaume-Uni, Allemagne, Pays-Bas)"),
 ("Documents non consultés en intégralité","Disposer des derniers constats officiels","Cour des comptes, « Le développement des activités commerciales en centre-ville » (mars 2026)","Cour des comptes","Rapport le plus récent sur le sujet","Ouvert (ccomptes.fr)","Non consulté (erreur d'accès)","Haute","Lire le rapport et ajouter ses chiffres"),
 ("Documents non consultés en intégralité","Disposer des constats officiels sur les QPV","Rapport de la mission sur l'avenir du commerce de proximité (nov. 2025), version intégrale","Mission gouvernementale ; Banque des Territoires","Diagnostic propre aux QPV","Ouvert","Lu via des synthèses","Haute","Lire le rapport intégral"),
 ("Documents non consultés en intégralité","Disposer des données de l'ANRU","ANRU, « Le commerce dans les quartiers prioritaires en renouvellement urbain » (2025)","ANRU","Diagnostic commercial des quartiers en renouvellement urbain","Ouvert","Non consulté (erreurs serveur)","Haute","Réessayer le téléchargement"),
 ("Documents non consultés en intégralité","Disposer du rapport du Sénat","Sénat, rapport n° 910 (2022), version intégrale","Sénat","Chiffres détaillés sur l'offre périphérique","Ouvert","Lu via la page de synthèse","Moyenne","Lire le chapitre sur les causes"),
 ("Documents non consultés en intégralité","Disposer du rapport IGF / IGEDD","IGF / IGEDD, « La revitalisation commerciale des centres-villes »","IGF ; IGEDD","Évaluation des dispositifs","Ouvert","Non consulté","Moyenne","Lire le rapport"),
 ("Documents non consultés en intégralité","Disposer des travaux économétriques français","Quantin et Turner (2015), grandes surfaces et durée de vie des petits commerces alimentaires","Insee","Seule étude française identifiée sur l'effet d'une grande surface sur la survie des petits commerces","Actes des Journées de méthodologie statistique","Connu via la note du CAE","Haute","Retrouver le texte et ses résultats chiffrés"),
 ("Documents non consultés en intégralité","Vérifier les chiffres de vacance","Baromètres Codata et FACT, versions d'origine","Codata ; FACT","Les chiffres circulent via la presse avec des valeurs différentes","Partiellement payant","Lu via des relais","Moyenne","Demander les baromètres à Codata / FACT"),
 ("Documents non consultés en intégralité","Vérifier les répartitions des ventes","Rexecode (2024), répartition des ventes par lieu","Rexecode","Source des 67 % (internet compris)","À vérifier","Repris de la présentation","Moyenne","Retrouver la publication d'origine"),
 ("Documents non consultés en intégralité","Disposer des études historiques sur les quartiers","CREDOC, « Commerces et zones urbaines sensibles » et « Le commerce dans les cités »","CREDOC","Données anciennes sur le commerce en ZUS","Ouvert (PDF anciens)","Non exploités (PDF illisibles)","Basse","Lire les PDF"),
]

OWN = [
 # indicateur, valeur, unité, période, champ
 ("Commerces employeurs en zones périphériques (Cerema EmpCom)",28742,"établissements","2012","1 372 sites, tampon de 50 m ; NAF 47.1 à 47.7 ; employeurs"),
 ("Commerces employeurs en zones périphériques",35775,"établissements","2025","Idem"),
 ("Évolution des commerces employeurs en zones périphériques",24.5,"%","2012-2025","Idem"),
 ("Commerces employeurs dans les centres-villes",61526,"établissements","2012","Cercle de 300 à 700 m autour de la mairie, 2 128 communes de 5 000 hab. et plus (hors Paris, Lyon, Marseille)"),
 ("Commerces employeurs dans les centres-villes",55973,"établissements","2025","Idem"),
 ("Évolution des commerces employeurs dans les centres-villes",-9.0,"%","2012-2025","Idem"),
 ("Commerces employeurs dans les QPV",12964,"établissements","2012","1 362 QPV 2024 (code QPV de la géolocalisation Sirene)"),
 ("Commerces employeurs dans les QPV",12169,"établissements","2025","Idem"),
 ("Évolution des commerces employeurs dans les QPV",-6.1,"%","2012-2025","Idem"),
 ("Évolution de tous les établissements (employeurs ou non) en zones périphériques",35.4,"%","2012-2025","Idem, tous établissements actifs"),
 ("Évolution de tous les établissements dans les centres-villes",-2.6,"%","2012-2025","Idem"),
 ("Évolution de tous les établissements dans les QPV",4.6,"%","2012-2025","Idem"),
 ("Croissance annuelle des commerces employeurs en périphérie",3.07,"% par an","2012-2016","Idem"),
 ("Croissance annuelle des commerces employeurs en périphérie",0.31,"% par an","2022-2025","Idem"),
 ("Croissance annuelle des commerces employeurs dans les centres-villes",-1.15,"% par an","2022-2025","Idem"),
 ("Écart d'évolution entre les QPV et le reste de leur commune",-16.5,"points","2012-2025","510 QPV comptant au moins 5 commerces employeurs en 2012 ; QPV −8,2 %, reste de la commune +8,3 %"),
 ("Habillement, commerces employeurs dans les centres-villes",-25.3,"%","2012-2025","NAF 47.71"),
 ("Chaussures et maroquinerie, commerces employeurs dans les QPV",-42.4,"%","2012-2025","NAF 47.72"),
 ("Habillement et chaussures, commerces employeurs en périphérie",-5.6,"%","2019-2025","NAF 47.71-47.72 ; pic en 2019"),
 ("Part des centres-villes à moins de 10 km d'une grande zone commerciale",89,"%","2021","Distance au contour EmpCom le plus proche ; médiane 2,5 km"),
 ("Effet estimé de l'ouverture nette d'une grande surface à moins de 10 km sur les commerces du centre",0.26,"point par période","2012-2025","Panel à effets fixes ; IC 95 % [−0,67 ; +1,20] : pas d'effet significatif"),
 ("Effet de la surface commerciale périphérique à moins de 10 km (modèle en coupe)",-0.08,"point par log-hectare","2012-2025","IC 95 % [−1,0 ; +0,9] : pas d'effet significatif"),
]
